---
subtitle: "DRAFT: for discussion only"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(mbbs)
library(dplyr)
library(tidyr)
library(ggplot2)
library(sparkline)
library(DT)
library(ggiraph)
```

```{r data_prep}
pre_dt <- mbbs %>% 
  filter(!is.na(spec_code)) 

# remove species only observed in one year
analysis_species <- pre_dt %>%
  group_by(spec_code, year) %>%
  summarise(dummy = sum(count) > 1) %>%
  group_by(spec_code) %>%
  summarise(nyears = sum(dummy)) %>%
  filter(nyears > 1)

analysis_dt <- pre_dt %>%
  right_join(analysis_species, by = "spec_code") 

analysis_dt_grouped <- analysis_dt %>%
  group_by(year, common_name, sci_name, spec_code) %>%
  summarise(count = mean(count)) %>%
  ungroup() %>%
  complete(
   nesting(common_name, sci_name, spec_code),
   year = full_seq(year, 1), 
   fill = list(count = 0)
  ) 
 

tot_sp_cnt <- length(unique(pre_dt$spec_code))
ana_sp_cnt <- length(unique(analysis_dt_grouped$spec_code))
species <- unique(analysis_dt_grouped$common_name)

```

From 1999-2018, `r tot_sp_cnt` different species were observed. For these analyses, species observed in a single year were excluded, leaving `r ana_sp_cnt` for analysis of trends.

```{r functions}
plot_trend <- function(dt, dt_grouped){
  ggplot(
    data = dt,
    aes(x = year, y = count)
  ) + 
  geom_line(
    data = dt,
    aes(group = route),
    # aes(group = route, tooltip = route, data_id = route), 
    color = "grey80",
    size  = 0.25
  ) +
  geom_line(
    data = dt_grouped,
  ) + 
  geom_point(
    data = dt_grouped,
    # aes(tooltip = round(count, 2)),
    size = 1
  ) + 
  scale_y_continuous(
    "Count",
    expand = c(0, 0),
    limits = c(0, max(dt[["count"]]) + 1)
  ) +
  scale_x_continuous(
    "Year",
    expand = c(.01, 0),
    breaks = seq(2000, 2018, by = 2)
  ) +
  stat_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  theme(
    panel.grid.major = element_line(color = "grey95"),
    panel.grid.minor = element_blank(),
    axis.title.x     = element_blank(),
    axis.title.y     = element_text(angle = 0, vjust = 0.5),
    axis.text.x      = element_text(hjust = 1, angle = 45, vjust = 1)
  )
}

# interactive_plot <- function(plot){
#   x <- girafe( code = print(plot), width_svg = 3, height_svg = 2)
#   girafe_options(x, opts_hover(css = "stroke:orange;stroke-width:2px;"))
# }

# plot_to_string <- function(plot){
#  htmltools::as.tags(plot)
# }

convert_img <- function(plot, width, height){
  tmpFile <- tempfile(fileext = ".png")
  ggsave(filename = tmpFile, plot = plot, width = width, height = height, dpi = 72)
  knitr::image_uri(tmpFile)
  
}

plot_sparkline <- function(x){
  as.character(htmltools::as.tags(
    sparkline(
      x,
      fillColor = FALSE,
      normalRangeMin = -diff(range(x)) * 0.09,
      normalRangeMax =  diff(range(x)) * 0.09,
      spotColor      = FALSE,
      minSpotColor   = FALSE,
      maxSpotColor   = FALSE
    )))
}

create_details <- function(common_name, sci_name, img_trend){
  
  more_link <- sprintf("https://www.allaboutbirds.org/guide/%s", 
                       stringr::str_replace_all(common_name, " ", "_"))
  
  htmltools::div(
    htmltools::p(
      htmltools::a(href = more_link, sci_name)
   ),
    htmltools::img(src = "noun_Bird_2164644.png"),
    img_trend
  )
}

```

```{r, warning = FALSE}
analysis_dt <- analysis_dt %>%
  group_by(common_name, sci_name, spec_code) %>%
  tidyr::nest()


result_dt <- analysis_dt_grouped %>%
  group_by(common_name, sci_name, spec_code) %>%
  tidyr::nest(.key = "data_grouped") %>% 
  left_join(
    analysis_dt, by = c("common_name", "sci_name", "spec_code")
  ) %>% mutate(
    lm             = purrr::map(data_grouped, ~ lm(count ~ year, data = .x)),
    rate_of_change = purrr::map_dbl(lm, ~ coef(.x)[2]),
    rate_of_change = round(rate_of_change, 3), 
    sparkline      = purrr::map_chr(data_grouped, ~ plot_sparkline(.x$count)),
    trend_plot     = purrr::map2(
      .x = data,
      .y = data_grouped,
      .f = ~ plot_trend(.x, .y) %>%
        convert_img(width = 6.5, height = 5) %>%
        htmltools::img(src = .)),
    details        = purrr::pmap(
      .l = list(x = common_name, y = sci_name, z = trend_plot),
      .f = function(x, y, z) {as.character(create_details(x, y, z)) }
    )
    
  )

table_dt <- result_dt %>%
  select(`Common name` = common_name, `Trend` = sparkline, 
         `Rate of change` = rate_of_change, details)
```

```{r}
tab <- datatable(
  cbind(' ' = '&oplus;', table_dt), 
  escape = FALSE,
  options = list(
    paging     = FALSE,
    bInfo      = FALSE,
    columnDefs = list(
      list(visible = FALSE, targets = c(0, 5)),
      list(orderable = FALSE, className = 'details-control', targets = c(1, 5))
    )
  ),
  callback = JS("
  table.column(1).nodes().to$().css({cursor: 'pointer'});
  var format = function(d) {
    return d[5];
  };
  table.on('click', 'td.details-control', function() {
    var td = $(this), row = table.row(td.closest('tr'));
    if (row.child.isShown()) {
      row.child.hide();
      td.html('&oplus;');
    } else {
      row.child(format(row.data())).show();
      td.html('&CircleMinus;');
    }
  });"
)
)
tab$dependencies <- append(tab$dependencies, htmlwidgets:::getDependency("sparkline"))
# tab$dependencies <- append(tab$dependencies, htmlwidgets:::getDependency("girafe", package = "ggiraph"))
```
```{r show_table, echo=FALSE}
tab
```



